name: Build Roll a Ball with NIS
on:
  push:
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Init submodule
        run: git submodule update --init --force

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: RollABall/
          buildMethod: BuildRollABall.WindowsBuildForRollABallFromCommandLine
          targetPlatform: StandaloneWindows
          customImage: 'unityci/editor:2021.3.16f1-base-0'
          
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: RollABall 
          path: RollABall/RollABallWindowsTest
